"""Target v1.2.15 wire contract registry and validation."""

from .registry import (
    APPROVED_PACKAGE_REVISION,
    ContractDefinition,
    ContractError,
    ContractType,
    TargetContract,
    contract_digest,
    get_contract_definition,
    implemented_contract_registry,
    parse_contract,
    validate_contract,
)
from .bindings import (
    APPROVED_CONTRACT_EDGES,
    BindingRole,
    ContractBindingError,
    ContractEdge,
    approved_contract_graph,
    contract_body,
    require_digest_binding,
    require_expected_fields,
    require_matching_fields,
    validate_contract_edge,
    validate_order_spec_construction_binding,
    validate_position_config_pin_binding,
)

__all__ = [
    "APPROVED_CONTRACT_EDGES",
    "APPROVED_PACKAGE_REVISION",
    "BindingRole",
    "ContractBindingError",
    "ContractDefinition",
    "ContractEdge",
    "ContractError",
    "ContractType",
    "TargetContract",
    "approved_contract_graph",
    "contract_body",
    "contract_digest",
    "get_contract_definition",
    "implemented_contract_registry",
    "parse_contract",
    "require_digest_binding",
    "require_expected_fields",
    "require_matching_fields",
    "validate_contract",
    "validate_contract_edge",
    "validate_order_spec_construction_binding",
    "validate_position_config_pin_binding",
]
