"""Market data normalization boundary."""

from .bybit import (
    BybitCandle,
    BybitInstrument,
    BybitTicker,
    parse_linear_instrument,
    parse_linear_ticker,
    parse_spot_candles,
    parse_spot_instrument,
    parse_spot_ticker,
)
from .futures import ContractCategory, FuturesAccountState, FuturesInstrumentMetadata, MarketRegimeContext, MarketRegimeLabel, RegimeCapability
from .futures_runtime import FuturesMarketEvent, futures_event_from_completed_candle, volume_window_from_futures_event
from .models import MarketObservation
from .raw_trades import (
    BYBIT_PUBLIC_TRADE_ARCHIVE_REVISION,
    RAW_TRADES_UNAVAILABLE_MISSING_ARCHIVE_DAY,
    BYBIT_PUBLIC_TRADE_ARCHIVE_SCHEMA,
    BybitRawTradeArchiveManifest,
    RAW_TRADES_UNAVAILABLE_ARCHIVE_COMPLETENESS_UNATTESTED,
    RAW_TRADES_UNAVAILABLE_ARCHIVE_MANIFEST_MISMATCH,
    RawTradeRecord,
    RawTradesBackfillResult,
    RawTradesSourceError,
    build_bybit_archive_raw_trades_response,
    build_raw_trades_response,
    build_unavailable_raw_trades_response,
    bybit_raw_trade_archive_manifest,
    bybit_public_trade_archive_url,
    instrument_symbol_for_logical_symbol,
    normalize_bybit_public_trade_rows,
    read_bybit_public_trade_archive,
)
from .regime import (
    REGIME_RULE_ID,
    REGIME_VERSION,
    RegimeEvaluationWindow,
    evaluate_market_regime,
    regime_business_key,
)

__all__ = [
    "BybitCandle",
    "BybitInstrument",
    "BybitTicker",
    "ContractCategory",
    "FuturesAccountState",
    "FuturesMarketEvent",
    "FuturesInstrumentMetadata",
    "MarketRegimeContext",
    "MarketRegimeLabel",
    "MarketObservation",
    "BYBIT_PUBLIC_TRADE_ARCHIVE_REVISION",
    "RAW_TRADES_UNAVAILABLE_MISSING_ARCHIVE_DAY",
    "BYBIT_PUBLIC_TRADE_ARCHIVE_SCHEMA",
    "BybitRawTradeArchiveManifest",
    "RAW_TRADES_UNAVAILABLE_ARCHIVE_COMPLETENESS_UNATTESTED",
    "RAW_TRADES_UNAVAILABLE_ARCHIVE_MANIFEST_MISMATCH",
    "REGIME_RULE_ID",
    "REGIME_VERSION",
    "RawTradeRecord",
    "RawTradesBackfillResult",
    "RawTradesSourceError",
    "RegimeCapability",
    "RegimeEvaluationWindow",
    "build_bybit_archive_raw_trades_response",
    "build_raw_trades_response",
    "build_unavailable_raw_trades_response",
    "bybit_raw_trade_archive_manifest",
    "bybit_public_trade_archive_url",
    "evaluate_market_regime",
    "futures_event_from_completed_candle",
    "instrument_symbol_for_logical_symbol",
    "normalize_bybit_public_trade_rows",
    "parse_linear_instrument",
    "parse_linear_ticker",
    "parse_spot_candles",
    "parse_spot_instrument",
    "parse_spot_ticker",
    "read_bybit_public_trade_archive",
    "regime_business_key",
    "volume_window_from_futures_event",
]
