"""Factual API adapter gateway helpers for target wire contracts."""

from .portfolio_data import (
    PortfolioDataGatewayError,
    build_portfolio_data_request,
    build_portfolio_data_response,
    fee_rate_item,
    instrument_metadata_item,
    portfolio_account_section,
    portfolio_position_item,
)
from .market_data import (
    MarketDataGatewayError,
    MarketDataSelection,
    build_market_data_request,
    build_market_data_response,
    coverage,
    dataset_payload,
    market_selection,
    market_selection_digest,
    market_selection_result,
)
from .native_profile import (
    NativeProfileConformanceError,
    NativeProfileConformanceReport,
    NativeProfileEvidence,
    NativeProfileStatus,
    bybit_demo_native_profile_conformance,
)
from .order_management import (
    OrderManagementGatewayError,
    build_hard_execution_facts,
    build_order_management_hard_response,
    build_order_management_operation_response,
    build_order_management_request,
    exchange_error,
    execution_fact_from_bybit,
    native_field_provenance,
    order_fact_from_bybit,
)

__all__ = [
    "MarketDataGatewayError",
    "MarketDataSelection",
    "NativeProfileConformanceError",
    "NativeProfileConformanceReport",
    "NativeProfileEvidence",
    "NativeProfileStatus",
    "OrderManagementGatewayError",
    "PortfolioDataGatewayError",
    "build_hard_execution_facts",
    "build_market_data_request",
    "build_market_data_response",
    "build_order_management_hard_response",
    "build_order_management_operation_response",
    "build_order_management_request",
    "bybit_demo_native_profile_conformance",
    "build_portfolio_data_request",
    "build_portfolio_data_response",
    "coverage",
    "dataset_payload",
    "exchange_error",
    "execution_fact_from_bybit",
    "fee_rate_item",
    "instrument_metadata_item",
    "market_selection",
    "market_selection_digest",
    "market_selection_result",
    "native_field_provenance",
    "order_fact_from_bybit",
    "portfolio_account_section",
    "portfolio_position_item",
]
